### ISSUE TITLE
Electron App crashes on startup on Catalina

### ISSUE THREAD

**Issue by manngo** [electron/electron-packager#1098] opened 2020-01-04 04:50 UTC
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

Electron app crashes on startup with the helpful message `… quit unexpectedly`.

* **Electron Version:**: That’s the problem …

* **Operating System:**:  MacOS 10.15.2 Catalina

* **Last Known Working Electron version:**: 5.0.13

### Expected Behavior

 Not crashing … ?

### Actual Behavior

After a few seconds, the application quits without ever showing a window. The OS message is `… quit unexpectedly`.

### To Reproduce

Start application

### Additional Information

I am using electron-packager to compile the application. Using `npm start` is fine.

I have tried the following:

- Comment out _all_ of the code in `main.js` and in `index.html`
- Using electron-rebuild to recompile node modules
- Various versions of electron before and after 5.0.13

I have also used electron-log and logged messages from `main.js`. Up to 5.0.13, of course, everything is fine. After that version, the main script runs, but anything from `app.on` or `ipcMain.on` doesn’t get triggered.

**Comment by malept** [comment] 2020-01-04 08:58
Please don't file the same issue in multiple projects. This is an issue not specific to Electron Packager.

Duplicate of https://github.com/electron/electron/issues/21674

**Closed by malept** 2020-01-04 08:58 UTC
Labels: invalid :x:
