### ISSUE TITLE
Electron Pacakging error - Operation not permitted, lstat

### ISSUE THREAD

**Issue by aruntech89** [electron/electron-packager#1064] opened 2019-10-28 05:10 UTC
Hi All,

Requirement:
We are building a desktop application using Electron & Python as business service to provide productivity tools to support our users.

### Issue Details

* **Electron Packager Version:**
    14.0.6
* **Electron Version:**
     6.0.7
* **Operating System:**
     Windows 10 (1803)
* **Last Known Working Electron Packager version:**:
  * 

### Expected Behavior
Our productivity tool desktop application in Win32 x64 as executable file.

### Actual Behavior

1) Using Electron-download we have downloaded the required binary in user\local\electron\cache
2) We have set electron_cache @ environment variable to user\local\electron\cache

Electron packager creates random temp files 
_**i.e. C:\Users\arun\AppData\Local\Temp\electron-download-wlbgwx\electron-v6.0.7-win32-x64.zip**_

which is not pointing to user\local\electron\cache where we have electron-download, downloaded the binaries.

### To Reproduce

**When we run the following command**
_electron-packager ./ --appname=UtilityTool --build-version=1.0.0 --download.cacheRoot=C:/Users/arun/AppData/Local/electron/Cache --no-asar --no-prune --platform=win32 --arch=x64 --icon=./images/UtilityTool.png --out ./dist/elenpm --overwrite_

**We are getting an issue**
PERM: operation not permitted, lstat 'C:\Users\arun\AppData\Local\Temp\electron-download-wlbgwx\electron-v6.0.7-win32-x64.zip'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 build-win32: electron-packager ./ --appname=UtilityTool --build-version=1.0.0 --download.cacheRoot=C:/Users/arun/AppData/Local/electron/Cache --no-asar --no-prune --platform=win32 --arch=x64 --icon=./images/UtilityTool.png --out ./dist/elenpm --overwrite
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 build-win32 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\arun\AppData\Roaming\npm-cache_logs\2019-10-24T06_17_59_536Z-debug.log

### Additional Information
Part of dependency from package.json

"devDependencies": {
"electron": "^6.0.7",
"electron-packager": "^14.0.6"
},
"dependencies": {
"@electron/get": "^1.5.0",
"debug": "^4.1.1",
"python-shell": "^1.0.8",
"rcedit": "^2.0.0",
"requirejs": "^2.3.6",
"sweetalert": "^2.1.2",
"username": "^5.1.0"
}

Please advise.
-Arun

**Comment by malept** [comment] 2019-10-28 15:28
This is a duplicate of #1019.

**Closed by malept** 2019-10-28 15:28 UTC
Labels: bug :bug:, duplicate

**Comment by aruntech89** [comment] 2019-11-01 08:29
Hi All,

Sorry for the delayed reply. Here in India its festival time

I tried the steps described in issue #1019 but no luck Im still facing the same issue.

When i run electron/get to download same error arises so i have logged an issue for assistance in electron/get as well. Please find the link below

https://github.com/electron/get/issues/122

**I have a question related to electron-packager,** How do i tell the electron-packager to pick the binary file from my local file system which i have downloaded using electron-download and placed in user\local\electron\cache

By default now it is trying to download the binaries wherever i run the command. If i can avoid that maybe i have a chance of building the application. Please advise 

Thank You
`Arun

**Comment by malept** [comment] 2019-11-01 15:46
> **I have a question related to electron-packager,** How do i tell the electron-packager to pick the binary file from my local file system which i have downloaded using electron-download and placed in user\local\electron\cache

This is https://github.com/electron/electron-packager/issues/187
