### ISSUE TITLE
Build mac app on windows EPERM error

### ISSUE THREAD

**Issue by LorenzoDelpi** [electron/electron-packager#1194] opened 2020-12-04 15:08 UTC
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

Electron Version:
11.0.3
Electron Packager Version:
15.1.0
Operating System:
 Windows 10 Pro (1909)

### Expected Behavior
I' am building a app for darwin os on a windows system with the following instruction:
`electron-packager . HyperloopUPV --overwrite --asar --platform=darwin --arch=x64  --prune --out=release`
I expected to create the app with no errors

### Actual Behavior
The folder with the app is created and apparentely there is all. However, the execution is interruppet by the following error:

EPERM: operation not permitted, stat 'C:\Users\LORENZ~1\AppData\Local\Temp\electron-packager\darwin-x64\HyperloopUPV-darwin-x64\HyperloopUPV.app\Contents\Frameworks\Squirrel.framework\Versions\Current'

It seems is like a permissions error, so i have run with administrator permissions and abilitate symlink, but doesn't work
I ve run it with the DEBUG variable and these are the final statements before the error

` electron-packager Running asar with the options {} +1m
  electron-packager Renaming Electron to HyperloopUPV in C:\Users\LORENZ~1\AppData\Local\Temp\electron-packager\darwin-x64\HyperloopUPV-darwin-x64\Electron.app\Contents\MacOS +9s
  electron-packager Renaming Electron Helper to HyperloopUPV Helper in C:\Users\LORENZ~1\AppData\Local\Temp\electron-packager\darwin-x64\HyperloopUPV-darwin-x64\Electron.app\Contents\Frameworks\Electron Helper.app\Contents\MacOS +15ms
  electron-packager Renaming Electron Helper.app to HyperloopUPV Helper.app in C:\Users\LORENZ~1\AppData\Local\Temp\electron-packager\darwin-x64\HyperloopUPV-darwin-x64\Electron.app\Contents\Frameworks +16ms
  electron-packager Moving C:\Users\LORENZ~1\AppData\Local\Temp\electron-packager\darwin-x64\HyperloopUPV-darwin-x64 to release\HyperloopUPV-darwin-x64 +16ms
EPERM: operation not permitted, stat 'C:\Users\LORENZ~1\AppData\Local\Temp\electron-packager\darwin-x64\HyperloopUPV-darwin-x64\HyperloopUPV.app\Contents\Frameworks\Squirrel.framework\Versions\Current'`

### To Reproduce
I ve tried in a pc with mac and it works perfectly, so the prolem mus t be in my pc with some local variable, there is no vpn or something similar, issue related with #933

**Comment by malept** [comment] 2020-12-04 18:08
I'm closing this as a duplicate of #933. The advice in [these](https://github.com/electron/electron-packager/issues/933#issuecomment-455801452) [comments](https://github.com/electron/electron-packager/issues/933#issuecomment-455807179) are still applicable, although you can add GitHub Actions to the CI list.

**Closed by malept** 2020-12-04 18:08 UTC
Labels: duplicate

**Comment by LorenzoDelpi** [comment] 2020-12-04 23:05
I read the comments, but no one  works.

**Comment by malept** [comment] 2020-12-04 23:14
It works for me when I set up GitHub Actions with a macOS instance to package a `darwin` target.

**Comment by LorenzoDelpi** [comment] 2020-12-04 23:16
could you explain better please? i don't understand what you mean exactly

**Comment by malept** [comment] 2020-12-04 23:27
Realistically speaking, you can only create Electron apps for macOS targets on macOS hosts. This is for at least a couple of reasons, some of which I will mention here:

* Windows support for symlinks _(which are used in the macOS Electron.app folder structure)_ works very inconsistently.
* As stated in the [code signing documentation](https://www.electronjs.org/docs/tutorial/code-signing), recent versions of macOS have made it very difficult to run unsigned apps in their operating system, and the only OS where you can sign apps for macOS is, unsurprisingly, macOS.

So the options you have to create a macOS-targeted app (i.e., `electron-packager --platform=darwin`) are:

1. Buy a Mac
2. Use a continuous integration provider which has macOS support

> It works for me when I set up GitHub Actions with a macOS instance to package a `darwin` target.

This means that I can set up [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions) to use a worker with macOS installed and run Electron Packager to bundle, customize, sign, and notarize a macOS-targeted app.

----

If you need more assistance, please use one of the [community forums](https://electronjs.org/community).

**Comment by VictorCallejas** [comment] 2020-12-04 23:45
This is nonsense I have been able to build electron apps targeting darwin on linux machines using circleCI

**Comment by malept** [comment] 2020-12-04 23:46
@VictorCallejas you can certainly build it on Linux machines, but you can't sign/notarize it there.

**Comment by VictorCallejas** [comment] 2020-12-04 23:49
That makes sense

**Comment by LorenzoDelpi** [comment] 2020-12-04 23:55
@malept thanks for the inputs, you know how i can build it without notarize it?

**Comment by malept** [comment] 2020-12-05 00:02
@LorenzoDelpi if you're distributing your app to customers using macOS, I **highly recommend** that you sign **and** notarize your app. Otherwise your users' experience installing and running your app the first time will not be good.

That being said, if you understand the risks and you'd like to package your app without signing/notarization on a Windows host for macOS targets, use [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) instead of CMD/powershell/git bash.

**Comment by LorenzoDelpi** [comment] 2020-12-05 00:30
@malept @VictorCallejas  The problem is with the temp folder and the permissions inside it to move files. I' ve solved the problem with specifying a new temporary director with --tmpdir.
Maybe it could be a w10 problem with the permission system, i always run it with admin but idk
