### ISSUE TITLE
packaging windows app does not work after upgrading to OSX 10.15

### ISSUE THREAD

**Issue by neuronflow** [electron/electron-packager#1055] opened 2019-10-08 18:49 UTC
### Preflight Checklist

* [X] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [X] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
13.1.1
  * 
* **Electron Version:**
  * 
4.1.4
* **Operating System:**
  * 
OSX 10.15
* **Last Known Working Electron Packager version:**:
  * 
13.1.1 / 14.0.6

### Expected Behavior

package all apps

### Actual Behavior

when packaging the windows app the following error msgs appear:

13.1.1:

Unhandled rejection Error: spawn Unknown system error -86
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at spawn (child_process.js:551:9)
    at module.exports (/Users/meow/data/phd/phd_projects/pipeline/code/elephant_client/node_modules/rcedit/lib/rcedit.js:47:15)
    at P (/Users/meow/data/phd/phd_projects/pipeline/code/elephant_client/node_modules/electron-packager/node_modules/pify/index.js:32:6)
    at new Promise (<anonymous>)
    at /Users/meow/data/phd/phd_projects/pipeline/code/elephant_client/node_modules/electron-packager/node_modules/pify/index.js:6:9
    at ret (/Users/meow/data/phd/phd_projects/pipeline/code/elephant_client/node_modules/electron-packager/node_modules/pify/index.js:56:76)
    at getIconPath.then.icon (/Users/meow/data/phd/phd_projects/pipeline/code/elephant_client/node_modules/electron-packager/win32.js:95:39)

14.0.6:
Packaging app for platform darwin x64 using electron v4.1.4
Packaging app for platform mas x64 using electron v4.1.4
Packaging app for platform linux x64 using electron v4.1.4
Packaging app for platform win32 x64 using electron v4.1.4
(node:16768) UnhandledPromiseRejectionWarning: Error: spawn Unknown system error -86
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at spawn (child_process.js:551:9)
    at Promise (/Users/meow/data/phd/phd_projects/pipeline/code/elephant_client/node_modules/rcedit/lib/rcedit.js:44:19)
    at new Promise (<anonymous>)
    at module.exports (/Users/meow/data/phd/phd_projects/pipeline/code/elephant_client/node_modules/rcedit/lib/rcedit.js:43:10)
    at WindowsApp.runRcedit (/Users/meow/data/phd/phd_projects/pipeline/code/elephant_client/node_modules/electron-packager/src/win32.js:94:31)
(node:16768) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:16768) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
WARNING: signing is required for mas builds. Provide the osx-sign option, or manually sign the app later.

**Comment by antelle** [comment] 2019-10-08 19:57
Hi! Got this as well. I guess, that's because `wine` is not x64 and doesn't work on macOS Catalina: https://forum.winehq.org/viewtopic.php?f=9&t=32590

**Comment by antelle** [comment] 2019-10-08 20:06
Created an issue in `rcedit`: https://github.com/electron/node-rcedit/issues/51

**Comment by malept** [comment] 2019-10-08 20:22
I'm going to close this since this is rcedit-specific. You can track progress in the node-rcedit bug you filed.

**Comment by neuronflow** [comment] 2019-10-08 20:23
thanks for the headsup..damn had I known about this issue before I would not have done the update -_-

**Comment by antelle** [comment] 2019-10-08 20:23
I guess, we'll still need to upgrade `rcedit` when they fix it.

**Closed by malept** 2019-10-08 20:22 UTC
Labels: bug :bug:, invalid :x:

**Comment by antelle** [comment] 2019-10-08 21:13
Maybe it makes sense to switch to another tool for writing icons? There are tools to read PE format in python, for example [pefile](https://github.com/erocarrera/pefile). Example of icon extraction using it: https://github.com/firodj/extract-icon-py.

**Comment by malept** [comment] 2019-10-08 21:19
It's not just icons, there are also some Windows metadata (including a strange XML blob embedded in the EXE for administrative rights).

I would rather not require Python to be installed on top of needing Node for Electron Packager.

**Comment by antelle** [comment] 2019-10-08 21:21
Well, Python is preinstalled on mac and exists everywhere on linux. The problem is, if there's complex information, `pefile` can produce broken results 😞

**Comment by antelle** [comment] 2019-10-09 21:18
I've solved it this way:

1. make a VM with Ubuntu+wine (use [this hack](https://forums.virtualbox.org/viewtopic.php?f=39&t=93419&start=30) to fix VirtualBox crashes on macOS Catalina)
2. remove wine
3. add a script called `wine` and inside this script upload everything to a VM, after which run `wine` there
4. override arguments, if necessary

Seems to be working fine here.
