### ISSUE TITLE
windows builds fail on MacOS 10.15 catalina

### ISSUE THREAD

**Issue by JarJarBernie** [electron/electron-packager#1061] opened 2019-10-23 19:01 UTC
Since upgrading to 10.15 Catalina electron-packager fails to build .exe files for windows. It simply throws this error:

> spawn Unknown system error -86

the command i used for my builds:
`electron-packager . myapp --overwrite --asar --platform=win32 --arch=ia32 --icon=myapproot/src/assets/icons/windows/icon.ico --prune=true --out=release-builds --version-string.CompanyName=myapp --version-string.FileDescription=CE --version-string.ProductName="myapp"`

My electron-packager version is 14.0.6.

Building for mac is still working fine.
Under 10.14 Mojave Windows builds were working too.

Am I doing something wrong or is this a catalina issue?

Hope anyone can help me.

Thank you

Bernhard

**Comment by malept** [comment] 2019-10-23 19:03
This is a duplicate of https://github.com/electron/electron-packager/issues/1055

**Closed by malept** 2019-10-23 19:03 UTC
Labels: bug :bug:, build-host:mac :apple:, build-target:windows, duplicate
