### ISSUE TITLE
Support reproducible builds

### ISSUE THREAD

**Issue by DaniellMesquita** [electron/electron-packager#1102] opened 2020-01-14 00:47 UTC
https://reproducible-builds.org/

**Comment by DaniellMesquita** [comment] 2020-01-22 01:41
https://reproducible-builds.org/

**Comment by malept** [comment] 2020-01-22 06:12
I'm closing this issue due to the vague nature of the request.

Electron Packager itself does not compile any code, it merely customizes a prebuilt Electron binary and bundles it with a JavaScript-based application. If you want to ensure that Electron itself can be built reproducibly, make sure that the Chromium and Node projects can be built in that manner. Then, if you can give precise steps to show that compiling the C++ source code of Electron itself multiple times for the same target platform/architecture combination does not result in the same binary, please file an issue in the [Electron issue tracker](https://github.com/electron/electron/issues/new/choose) with detailed steps that you took to get to this conclusion, so others can replicate the behavior.

That being said, if you can provide precise steps to show that runs of Electron Packager with the exact same options do not produce bit-for-bit identical Electron app bundles, feel free to file a different bug with much more detail than this issue.

**Closed by malept** 2020-01-22 06:12 UTC
Labels: invalid :x:
