### ISSUE TITLE
electron-packager doesn't copy the dependency completely

### ISSUE THREAD

**Issue by belloyang** [electron/electron-packager#1289] opened 2021-10-04 14:42 UTC
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/main/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
  * 15.4.0
* **Electron Version:** 
  * 8.2.0
* **Operating System:** 
  * macOS 11.5.2
* **Last Known Working Electron Packager version:**:
  * 11.0.0

### Expected Behavior

electron-packager is supposed to copy the dependency module completely. 

### Actual Behavior
It appears some folders are missing from the package.
The missing folders/files are including:
1. yarn.lock
2. node_modules/zone.js/dist
3. node_modules/rxjs/internal/operators/distinct*

### To Reproduce

I encounter this issue after I'm trying to upgrade electron to a newer version 8.2.0, which requires electron-packager >=14.0.4 according to this post: https://github.com/electron/electron/issues/19511
I use electron-forge in my project for building and packaging. the latest electron-forge is using electron-package@^11.0.0 for packaging, which causes crash on launch. I had to force electron-forge to use the newer version electron-packager@15.4.0 for packaging, which solves the crash issue but it complains the files (as mentioned above) are missing.

### Additional Information

My project was previously setup to include zone.js polyfill in index.html:
```
<script src="../node_modules/zone.js/dist/zone.js"></script> 
```
This has never been a problem until I upgrade electron-packager to use a newer version (.e.g. 15.4.0), which reports error:
```
failed to load resource   net::ERR_NOT_IMPLEMENTED                         zone.js
```
I had to remove the polyfill in index.html to avoid this error, I'm not sure if this is relevant to the bug of electron-packager.

Another thing I found strange is that, in my project I put `zone.js`, `rxjs`, @angular/common, @angular/compiler, etc in `devDependencies`, and electron-packager@11.0.0 seem to automatically copy them to the final package. but electron-packager@15.4.0 doesn't do so. I had to move `zone.js`, `rxjs`, ... to `dependencies` in package.json, this leads to the missing folders/files I mentioned above

 I would highly appreciate if any of you could shed some light in the issue. Many thanks!

**Comment by malept** [comment] 2021-10-04 14:53
Ignoring `yarn.lock` by default was added in [version 15.2.0](https://github.com/electron/electron-packager/releases/tag/v15.2.0).

Without knowing anything about your setup (because you didn't provide your configuration), it sounds like `dist` is being ignored. According to the [`ignore` docs](https://electron.github.io/electron-packager/v15.4.0/interfaces/electronpackager.options.html#ignore), it is a regular expression, so it would match the second and third paths in your list. I would recommend being more precise about that ignore regular expression

I'm closing this issue because this is a question and not a bug/feature request.

If you need more assistance, please use one of the [community forums](https://electronjs.org/community), including the [Electron Discord server](https://discord.gg/electron).

**Closed by malept** 2021-10-04 14:53 UTC
Labels: question :question:
