### ISSUE TITLE
Enable ASAR by default

### ISSUE THREAD

**Issue by dragonDScript** [electron/electron-packager#1183] opened 2020-10-04 21:54 UTC
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
ASAR is a compression method used in Electron - somewhat similar to other formats. While this format, asar, can cause some issues, it's vital to enable it by default, so apps don't weight a lot.

### Proposed Solution
Enable ASAR by default (i can make a pr).

### Alternatives Considered
Add a warning if you're not using ASAR telling you that it's recommended to use it.

### Additional Information
This feature is true by default in electron builder, which is a very popular alternative to packager. 
![imagen](https://user-images.githubusercontent.com/46191980/95027983-0517a580-069d-11eb-8e47-5e006659d1c2.png)

**Comment by malept** [comment] 2020-10-04 21:56
Duplicate of #35

**Closed by malept** 2020-10-04 21:56 UTC
Labels: enhancement
