### ISSUE TITLE
Cross Compiling on Catalina

### ISSUE THREAD

**Issue by manngo** [electron/electron-packager#1060] opened 2019-10-10 05:44 UTC
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

Cross Compiling a Windows version on Catalina no longer works.

### Discussion

This is not actually a bug with electron-packager but an issue with Wine, which is needed to to the job. Wine is currently a 32bit product, and Catalina, of course, doesn’t support 32bits.

With respect, Apple have been telling everyone for over 2 years that 32Bit support would be dropped, started issuing warnings last year, and did make a big point of telling everyone again when Catalina was announced. Apparently, it still came as a surprise when it happened.

Moving on, I have had success building inside VirtualBox. To be honest, I had to set up Electron in my virtual machine anyway so that I could more fully test the Windows version, so compiling in Windows was only a minor inconvenience.

I did have issues with running VirtualBox in Catalina, but I managed to fix it (after some searching) by removing VirtulBox from `Security & Privacy | Privacy | Accessibility`.

It’s not as convenient as it used to be, but it’s still a workable solution.

**Comment by malept** [comment] 2019-10-10 15:24
This is a duplicate of https://github.com/electron/electron-packager/issues/1055

**Closed by malept** 2019-10-10 15:24 UTC
Labels: bug :bug:, duplicate
